### ISSUE TITLE
HiDPI background image detected failed

### ISSUE THREAD

**Issue by medns** [al45tair/dmgbuild#19]
HiDPI background image can not auto detected, because the following code 

https://github.com/al45tair/dmgbuild/blob/93fde0d01950d8ad43a3720c0dae75a26ed3b2d5/dmgbuild/core.py#L468

**Comment by al45tair** [comment]
I don't think you wrote all of what you wanted to write here, but it looks to me as if the code there should work. The image needs to have the same name as the base image, but it needs an @<scale>x in it. e.g. if the base image is called background.png, the code looks for background@2x.png, background@4x.png and so on.

Maybe you can describe what you were doing, what you expected and how dmgbuild's behaviour differed from your expectations, so that I can understand why you filed this ticket?

**Comment by al45tair** [comment]
Closing as there was no reply and I think this works.
